compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-2-release-amd64

task:

  install_script:
  - pkg install -y gitup

  clone_src_script:
  - gitup stable

  script:
  - make
